name: Build LaTeX document on Pull Request

on:
  pull_request:
    branches:
      - '*'

env:
  REPO_URL: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: new

      - name: Get commit hash and branch name
        id: commit_info
        run: |
          cd new
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          # Replace invalid characters in branch name using regex
          BRANCH=$(echo "${BRANCH}" | sed 's/[^a-zA-Z0-9\-]/_/g')
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          # Change TeX Live version as needed
          texlive_version: 2023
          working_directory: new/latex_project
          root_file: |
            *.tex

      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX_PDF-${{ env.HASH }}
          path: new/latex_project/*.pdf

      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: old

      - name: Install latexdiff
        run: sudo apt-get install -y latexdiff --no-install-recommends

      - name: Run latexdiff for each document
        run: |
          for file in new/latex_project/*.tex; do
            filename=$(basename "$file" .tex)
            if [ -e "old/latex_project/${filename}.tex" ] && [ -e "$file" ]; then
              latexdiff -t UNDERLINE --verbose --no-links --flatten --allow-spaces --graphics-markup=0 --disable-citation-markup old/latex_project/${filename}.tex new/latex_project/${filename}.tex > new/latex_project/${filename}_diff.tex
            fi
          done

      - name: Compile LaTeX difference documents
        continue-on-error: true
        uses: xu-cheng/latex-action@v3
        with:
          # Change TeX Live version as needed
          texlive_version: 2023
          working_directory: new/latex_project
          continue_on_error: true
          args: -f -pdf -interaction=nonstopmode
          root_file: |
            *_diff.tex

      - name: Upload PDF difference documents
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX_PDF_Difference-${{ env.HASH }}
          path: new/latex_project/*_diff.pdf

      - name: Find comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
        if: always()

      - name: Post comment (success)
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            Hi, @${{ github.event.sender.login }}! :wave: <br>
            The LateX build (${{ env.HASH }}) has **succeeded**. [**Click here**](${{ env.LOG_URL }}) to download your results.
        env:
          LOG_URL: ${{ env.REPO_URL }}/actions/runs/${{ github.run_id }}?check_suite_focus=true

      - name: Post comment (failure)
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            Sorry, @${{ github.event.sender.login }}! :disappointed: <br>
            The LateX build (${{ env.HASH }}) has **failed**. [**Click here**](${{ env.LOG_URL }}) to see the build log.
        env:
          LOG_URL: ${{ env.REPO_URL }}/actions/runs/${{ github.run_id }}?check_suite_focus=true
        if: failure()
