name: Run Tests Python
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'python_project/src/**'
      - 'python_project/tests/**'
    branches:
      - '*'
jobs:
  test_python:
    name: Run Tests Python
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Setup Python Dependencies
      run: |
        pip install -e ./python_project
        pip install -r requirements.txt

    - name: Run Tests on Python Package
      run: |
        pytest python_project
